# Describes the format for available statistic import services

import_from_file:
  fields:
    filename:
      required: true
      example: "statisticdata.tsv"
      selector:
        text:
    timezone_identifier:
      required: true
      example: "Europe/Vienna"
      default: "Europe/Vienna"
      selector:
        text:
    delimiter:
      required: false
      example: \t
      default: \t
      selector:
        select:
          custom_value: true
          options:
            - '\t'
            - ";"
            - ","
            - "|"
    decimal:
      required: true
      example: false
      default: false
      selector:
        boolean:
    datetime_format:
      required: false
      example: "%d.%m.%Y %H:%M"
      default: "%d.%m.%Y %H:%M"
      selector:
        select:
          custom_value: true
          options:
            - "%d.%m.%Y %H:%M"
            - "%Y.%m.%d %H:%M"
            - "%Y-%m-%d %H:%M"
            - "%m/%d/%Y %H:%M"
            - "%d/%m/%Y %H:%M"
    unit_from_entity:
      required: false
      example: true
      default: true
      selector:
        boolean:
